### ISSUE TITLE
Cannot work with both servers in hosts.txt

### ISSUE THREAD

**Issue by nhattanmai91** [nedko/netspeed#1]
Hi,

I've got an issue when running your code. Please help me to figure this. 

tan@envy:~/Desktop/choi/netspeed-master$ make
gcc -Wall -Wextra -O2 netspeed.c -o netspeed
tan@envy:~/Desktop/choi/netspeed-master$ ls
GNUmakefile  gpl-3.0.txt  hosts.txt  netspeed  netspeed.c  README
tan@envy:~/Desktop/choi/netspeed-master$ ./netspeed d speedtest.mycosmos.gr
Generate network traffic. Written by Nedko Arnaudov.
4 worker(s)
POST body size: 3145728 bytes
mlockall() failed. 12 (Cannot allocate memory)
Cannot set scheduling policy 1 (Operation not permitted)

==> It is unable to finish, shows no result. The same issue with server "speedtest.mtel.bg".

How do you run this code? Did I do something wrong? @nedko

**Comment by nedko** [comment]
nhattanmai91 notifications@github.com writes:

> I've got an issue when running your code. Please help me to figure this. 
> 
> tan@envy:~/Desktop/choi/netspeed-master$ make
> gcc -Wall -Wextra -O2 netspeed.c -o netspeed
> tan@envy:~/Desktop/choi/netspeed-master$ ls
> GNUmakefile  gpl-3.0.txt  hosts.txt  netspeed  netspeed.c  README
> tan@envy:~/Desktop/choi/netspeed-master$ ./netspeed d speedtest.mycosmos.gr
> Generate network traffic. Written by Nedko Arnaudov.
> 4 worker(s)
> POST body size: 3145728 bytes
> mlockall() failed. 12 (Cannot allocate memory)
> Cannot set scheduling policy 1 (Operation not permitted)
> 
> ==> It is unable to finish, shows no result. The same issue with
> server "speedtest.mtel.bg".
> 
> How do you run this code? Did I do something wrong?

I don't see what is the problem. What you are trying to achieve?
The mlockall error is actually a warning, it does not prevent the
traffic generation.

**Comment by nhattanmai91** [comment]
Hi,

After the line "Cannot set scheduling policy 1 (Operation not permitted)", I see nothing else. No any speed result or signal of connecting.

I think something went wrong. Could you please show me the result when you run this code correctly?

**Comment by nedko** [comment]
nhattanmai91 notifications@github.com writes:

> After the line "Cannot set scheduling policy 1 (Operation not
> permitted)", I see nothing else. No any speed result or signal of
> connecting.
> 
> I think something went wrong. Could you please show me the result when
> you run this code correctly?

netspeed does not measure network speed. instead, in unix spirit of do
one thing and do it well, it attempts to generate network traffic with
minimal cpu pressure. you can measure the speed with other tool, for
example iftop. when you want netspeed to stop generating traffic, press
ctrl-c.

**Comment by nhattanmai91** [comment]
Hi,
I understood. Thanks so much for your help. You're doing great
Tan M.
